development:
  paypal_account: bvduong76-facilitator-199@gmail.com
  paypal_host: https://www.sandbox.paypal.com
  app_host: http://3c215baa.ngrok.io 
production:
  paypal_account: bvduong76@gmail.com
  paypal_host: https://www.paypal.com
  app_host: