development:
  paypal_account: bvduong76-sandbox@gmail.com
  paypal_host: https://www.sandbox.paypal.com
  app_host: http://c9048fe3.ngrok.io 
production:
  paypal_account: bvduong76@gmail.com
  paypal_host: https://www.paypal.com
  app_host: 