development:
  paypal_account: bvduong76-sandbox@gmail.com
  paypal_host: https://www.sandbox.paypal.com
  app_host: http://1eaadedb.ngrok.io
production:
  paypal_account: bvduong76@gmail.com
  paypal_host: https://www.paypal.com
  app_host: 